package com.amonteiro.a01_supvincia.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF822CD3)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2C0051)
val md_theme_light_secondary = Color(0xFF5F6200)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE5EA5D)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1D00)
val md_theme_light_tertiary = Color(0xFF006D44)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF79FBB6)
val md_theme_light_onTertiaryContainer = Color(0xFF002111)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFA8A5A5)
val md_theme_light_onBackground = Color(0xFF1B0261)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B0261)
val md_theme_light_surfaceVariant = Color(0xFFE9DFEB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF302175)
val md_theme_light_inversePrimary = Color(0xFFDCB8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF822CD3)
val md_theme_light_outlineVariant = Color(0xFFCCC4CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDCB8FF)
val md_theme_dark_onPrimary = Color(0xFF480081)
val md_theme_dark_primaryContainer = Color(0xFF6700B5)
val md_theme_dark_onPrimaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_secondary = Color(0xFFC8CE43)
val md_theme_dark_onSecondary = Color(0xFF313300)
val md_theme_dark_secondaryContainer = Color(0xFF474A00)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5EA5D)
val md_theme_dark_tertiary = Color(0xFF5BDE9C)
val md_theme_dark_onTertiary = Color(0xFF003921)
val md_theme_dark_tertiaryContainer = Color(0xFF005232)
val md_theme_dark_onTertiaryContainer = Color(0xFF79FBB6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B0261)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF6041B4)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CE)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1B0261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF822CD3)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDCB8FF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFAD5DFF)